version: '3'

services:
  manageShopDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10
  manageShopDBM:
    image: manageshopdbm
    environment:
      - DATABASE_URL=manageShopDB
    depends_on:
      manageShopDB:
        condition: service_healthy
  manageShop:
    image: manageshop
    environment:
      - DATABASE_URL=manageShopDB
    depends_on:
      - manageShopDBM
