version: '3'

services:
#SHOP
  manageShopDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - shopdisk:/var/lib/mysql
    networks:
      - shopnet
  manageShopDBM:
    image: manageshopdbm
    environment:
      - DATABASE_URL=manageShopDB
    depends_on:
      manageShopDB:
        condition: service_healthy
    networks:
      - shopnet
  manageShop:
    image: sparkapp
    environment:
      - DATABASE_URL=manageShopDB
    depends_on:
      - manageShopDBM
    networks:
      - shopnet
    ports:
      - 5001:5001
  adminerShop:
    image: adminer
    ports:
      - 8083:8080
    networks:
      - shopnet
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - shopnet
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - shopnet
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - 8082:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - shopnet




#Accounts
  manageAccDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - accdisk:/var/lib/mysql
    networks:
      - accnet
  manageAccDBM:
    image: manageaccdbm
    environment:
      - DATABASE_URL=manageAccDB
    depends_on:
      manageAccDB:
        condition: service_healthy
    networks:
      - accnet
  manageAcc:
    image: manageacc
    environment:
      - DATABASE_URL=manageAccDB
    depends_on:
      - manageAccDBM
    networks:
      - accnet
    ports:
      - 5002:5002
  adminerAcc:
    image: adminer
    ports:
      - 8084:8080
    networks:
      - accnet


volumes:
  shopdisk:
  accdisk:

networks:
  shopnet:
  accnet:

