"""V 1,0

Revision ID: c23541aedd61
Revises: 62ec91c63648
Create Date: 2024-02-05 15:26:20.766823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23541aedd61'
down_revision = '62ec91c63648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_email', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'user_email')
    # ### end Alembic commands ###
